env:
    browser: true
    es2021: true
    node: true
extends:
    - "eslint-config-shaunburdick/typescript"
    - "react-app"
parserOptions:
    ecmaVersion: 12
    sourceType: module
    project: ./tsconfig.json
rules:
  "@typescript-eslint/naming-convention":
    - "error"
    - selector:
        - "function"
        - "variable"
      modifiers:
        - "exported"
      format:
        - PascalCase
